home_page:
    path: /
    controller: App\Controller\DefaultController::index

sign_up:
     path: /sign-up
     controller: App\Controller\SignupController::index

activate_account:
     path: /activate/{token}
     controller: App\Controller\ActivateController::index

forgot_password:
     path: /forgot-password
     controller: App\Controller\ForgotpasswordController::index

reset_password:
     path: /reset-password/{token}
     controller: App\Controller\ActivateController::reset

reset_password_success:
     path: /reset-password-success
     controller: App\Controller\ActivateController::success

login_info:
     path: /login-info
     controller: App\Controller\MyaccountController::login

password_info:
     path: /password-info
     controller: App\Controller\MyaccountController::password

verify_email:
     path: /myaccount-email-verify
     controller: App\Controller\MyaccountController::verify

before_logout:
     path: /before-logout-login
     controller: App\Controller\SignupController::beforelogout

myaccount_gallery:
     path: /my-gallery
     controller: App\Controller\MyaccountController::gallery

public_gallery:
     path: /pets-photo-gallery/{page}/{type}
     controller: App\Controller\GalleryController::index
     defaults:
        page: 1
        type: all
        
myaccount_gallery_edit:
     path: /my-gallery-edit/{token}
     controller: App\Controller\MyaccountController::galleryEdit


myaccount_gallery_delete:
     path: /my-gallery-delete/{token}
     controller: App\Controller\MyaccountController::galleryDelete

myaccount_gallery_list:
     path: /my-gallery-list
     controller: App\Controller\MyaccountController::galleryList


gallery_view:
     path: /photo-details/{id}
     controller: App\Controller\GalleryController::details

gallery_like:
     path: /photo-like/{id}
     controller: App\Controller\GalleryController::like
